/**
 * AUTO-GENERATED by fetch-vtpass-plans.js
 * Generated: 2026-07-30T12:18:39.443Z
 * VTPass URL: https://sandbox.vtpass.com/api
 * Margin applied: 15%
 *
 * DO NOT EDIT MANUALLY — run fetch-vtpass-plans.js to regenerate
 */

export const GENERATED_DATA_PLANS = [
  {
    "network": "MTN",
    "name": "N100 100MB - 24 hrs",
    "sizeGb": 0.09765625,
    "sizeLabel": "100MB",
    "price": 120,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "mtn-10mb-100"
  },
  {
    "network": "MTN",
    "name": "N200 200MB - 2 days",
    "sizeGb": 0.1953125,
    "sizeLabel": "200MB",
    "price": 230,
    "validityDays": 2,
    "category": "DAILY",
    "providerCode": "mtn-50mb-200"
  },
  {
    "network": "MTN",
    "name": "N1000 1.5GB - 30 days",
    "sizeGb": 1.5,
    "sizeLabel": "1.5GB",
    "price": 1150,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "mtn-100mb-1000"
  },
  {
    "network": "MTN",
    "name": "N2000 4.5GB - 30 days",
    "sizeGb": 4.5,
    "sizeLabel": "4.5GB",
    "price": 2300,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "mtn-500mb-2000"
  },
  {
    "network": "MTN",
    "name": "N1500 6GB - 7 days",
    "sizeGb": 6,
    "sizeLabel": "6GB",
    "price": 1730,
    "validityDays": 7,
    "category": "WEEKLY",
    "providerCode": "mtn-20hrs-1500"
  },
  {
    "network": "MTN",
    "name": "N2500 6GB - 30 days",
    "sizeGb": 6,
    "sizeLabel": "6GB",
    "price": 2880,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "mtn-3gb-2500"
  },
  {
    "network": "MTN",
    "name": "N3000 8GB - 30 days",
    "sizeGb": 8,
    "sizeLabel": "8GB",
    "price": 3450,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "mtn-data-3000"
  },
  {
    "network": "MTN",
    "name": "N3500 10GB - 30 days",
    "sizeGb": 10,
    "sizeLabel": "10GB",
    "price": 4030,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "mtn-1gb-3500"
  },
  {
    "network": "MTN",
    "name": "N5000 15GB - 30 days",
    "sizeGb": 15,
    "sizeLabel": "15GB",
    "price": 5750,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "mtn-100hr-5000"
  },
  {
    "network": "MTN",
    "name": "N6000 20GB - 30 days",
    "sizeGb": 20,
    "sizeLabel": "20GB",
    "price": 6900,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "mtn-3gb-6000"
  },
  {
    "network": "MTN",
    "name": "N10000 40GB - 30 days",
    "sizeGb": 40,
    "sizeLabel": "40GB",
    "price": 11500,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "mtn-40gb-10000"
  },
  {
    "network": "MTN",
    "name": "N15000 75GB - 30 days",
    "sizeGb": 75,
    "sizeLabel": "75GB",
    "price": 17250,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "mtn-75gb-15000"
  },
  {
    "network": "MTN",
    "name": "N20000 110GB - 30 days",
    "sizeGb": 110,
    "sizeLabel": "110GB",
    "price": 23000,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "mtn-110gb-20000"
  },
  {
    "network": "MTN",
    "name": "N1500 3GB - 30 days",
    "sizeGb": 3,
    "sizeLabel": "3GB",
    "price": 1730,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "mtn-3gb-1500"
  },
  {
    "network": "MTN",
    "name": "MTN N10,000 25GB SME Mobile Data ( 1 Month)",
    "sizeGb": 25,
    "sizeLabel": "25GB",
    "price": 11500,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "mtn-25gb-sme-10000"
  },
  {
    "network": "MTN",
    "name": "MTN N50,000 165GB SME Mobile Data (2-Months)",
    "sizeGb": 165,
    "sizeLabel": "165GB",
    "price": 57500,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "mtn-165gb-sme-50000"
  },
  {
    "network": "MTN",
    "name": "MTN N100,000 360GB SME Mobile Data (3 Months)",
    "sizeGb": 360,
    "sizeLabel": "360GB",
    "price": 115000,
    "validityDays": 90,
    "category": "SME",
    "providerCode": "mtn-360gb-sme-100000"
  },
  {
    "network": "MTN",
    "name": "MTN N600 2.5GB - 2 days",
    "sizeGb": 2.5,
    "sizeLabel": "2.5GB",
    "price": 690,
    "validityDays": 2,
    "category": "DAILY",
    "providerCode": "mtn-2-5gb-600"
  },
  {
    "network": "MTN",
    "name": "MTN N22000 120GB Monthly Plan + 80mins",
    "sizeGb": 120,
    "sizeLabel": "120GB",
    "price": 25300,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "mtn-120gb-22000"
  },
  {
    "network": "MTN",
    "name": "MTN 100GB 2-Month Plan",
    "sizeGb": 100,
    "sizeLabel": "100GB",
    "price": 23000,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "mtn-100gb-20000"
  },
  {
    "network": "MTN",
    "name": "MTN N30,000 160GB 2-Month Plan",
    "sizeGb": 160,
    "sizeLabel": "160GB",
    "price": 34500,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "mtn-160gb-30000"
  },
  {
    "network": "MTN",
    "name": "MTN N50,000 400GB 3-Month Plan",
    "sizeGb": 400,
    "sizeLabel": "400GB",
    "price": 57500,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "mtn-400gb-50000"
  },
  {
    "network": "MTN",
    "name": "MTN N75,000 600GB 3-Months Plan",
    "sizeGb": 600,
    "sizeLabel": "600GB",
    "price": 86250,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "mtn-600gb-75000"
  },
  {
    "network": "MTN",
    "name": "MTN N800 3GB - 2 days",
    "sizeGb": 3,
    "sizeLabel": "3GB",
    "price": 920,
    "validityDays": 2,
    "category": "DAILY",
    "providerCode": "mtn-3gb-800"
  },
  {
    "network": "MTN",
    "name": "MTN N2000 7GB - 7 days",
    "sizeGb": 7,
    "sizeLabel": "7GB",
    "price": 2300,
    "validityDays": 7,
    "category": "WEEKLY",
    "providerCode": "mtn-7gb-2000"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data Bundle - 50 Naira - 25MB  - 1Day",
    "sizeGb": 0.0244140625,
    "sizeLabel": "25MB",
    "price": 60,
    "validityDays": 1,
    "category": "DAILY",
    "providerCode": "airt-50"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data Bundle - 100 Naira - 75MB - 1Day",
    "sizeGb": 0.0732421875,
    "sizeLabel": "75MB",
    "price": 120,
    "validityDays": 1,
    "category": "DAILY",
    "providerCode": "airt-100"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data Bundle - 200 Naira - 200MB - 3Days",
    "sizeGb": 0.1953125,
    "sizeLabel": "200MB",
    "price": 230,
    "validityDays": 3,
    "category": "DAILY",
    "providerCode": "airt-200"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data Bundle - 300 Naira - 350MB - 7 Days",
    "sizeGb": 0.341796875,
    "sizeLabel": "350MB",
    "price": 350,
    "validityDays": 7,
    "category": "WEEKLY",
    "providerCode": "airt-300"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data Bundle - 500 Naira - 750MB - 14 Days",
    "sizeGb": 0.732421875,
    "sizeLabel": "750MB",
    "price": 580,
    "validityDays": 14,
    "category": "SME",
    "providerCode": "airt-500"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data Bundle - 1,000 Naira - 1.5GB - 30 Days",
    "sizeGb": 1.5,
    "sizeLabel": "1.5GB",
    "price": 1150,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "airt-1000"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data Bundle - 1,500 Naira - 3GB - 30 Days",
    "sizeGb": 3,
    "sizeLabel": "3GB",
    "price": 1730,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "airt-1500"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data Bundle - 2,000 Naira - 4.5GB - 30 Days",
    "sizeGb": 4.5,
    "sizeLabel": "4.5GB",
    "price": 2300,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "airt-2000"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data Bundle - 3,000 Naira - 8GB - 30 Days",
    "sizeGb": 8,
    "sizeLabel": "8GB",
    "price": 3450,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "airt-3000"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data Bundle - 4,000 Naira - 11GB - 30 Days",
    "sizeGb": 11,
    "sizeLabel": "11GB",
    "price": 4600,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "airt-4000"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data Bundle - 5,000 Naira - 15GB - 30 Days",
    "sizeGb": 15,
    "sizeLabel": "15GB",
    "price": 5750,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "airt-5000"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Binge Data - 1,500 Naira (7 Days) - 6GB",
    "sizeGb": 6,
    "sizeLabel": "6GB",
    "price": 1730,
    "validityDays": 7,
    "category": "WEEKLY",
    "providerCode": "airt-1500-2"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data Bundle - 10,000 Naira - 40GB - 30 Days",
    "sizeGb": 40,
    "sizeLabel": "40GB",
    "price": 11500,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "airt-10000"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data Bundle - 15,000 Naira - 75GB - 30 Days",
    "sizeGb": 75,
    "sizeLabel": "75GB",
    "price": 17250,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "airt-15000"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data Bundle - 20,000 Naira - 110GB - 30 Days",
    "sizeGb": 110,
    "sizeLabel": "110GB",
    "price": 23000,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "airt-20000"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data - 600 Naira - 1GB - 14 days",
    "sizeGb": 1,
    "sizeLabel": "1GB",
    "price": 690,
    "validityDays": 14,
    "category": "SME",
    "providerCode": "airt-600"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data - 1000 Naira - 1.5GB - 7 days",
    "sizeGb": 1.5,
    "sizeLabel": "1.5GB",
    "price": 1150,
    "validityDays": 7,
    "category": "WEEKLY",
    "providerCode": "airt-1000-7"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data - 2000 Naira - 7GB - 7 days",
    "sizeGb": 7,
    "sizeLabel": "7GB",
    "price": 2300,
    "validityDays": 7,
    "category": "WEEKLY",
    "providerCode": "airt-2000-7"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data - 5000 Naira - 25GB - 7 days",
    "sizeGb": 25,
    "sizeLabel": "25GB",
    "price": 5750,
    "validityDays": 7,
    "category": "WEEKLY",
    "providerCode": "airt-5000-7"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data - 400 Naira - 1.5GB - 1 day",
    "sizeGb": 1.5,
    "sizeLabel": "1.5GB",
    "price": 460,
    "validityDays": 1,
    "category": "DAILY",
    "providerCode": "airt-400-1"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data - 800 Naira - 3.5GB - 2 days",
    "sizeGb": 3.5,
    "sizeLabel": "3.5GB",
    "price": 920,
    "validityDays": 2,
    "category": "DAILY",
    "providerCode": "airt-800-2"
  },
  {
    "network": "AIRTEL",
    "name": "Airtel Data - 6000 Naira - 23GB - 30 days",
    "sizeGb": 23,
    "sizeLabel": "23GB",
    "price": 6900,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "airt-6000-30"
  },
  {
    "network": "GLO",
    "name": "Glo Data N100 -  105MB - 2 day",
    "sizeGb": 0.1025390625,
    "sizeLabel": "105MB",
    "price": 120,
    "validityDays": 2,
    "category": "DAILY",
    "providerCode": "glo100"
  },
  {
    "network": "GLO",
    "name": "Glo Data N200 -  350MB - 4 days",
    "sizeGb": 0.341796875,
    "sizeLabel": "350MB",
    "price": 230,
    "validityDays": 4,
    "category": "SME",
    "providerCode": "glo200"
  },
  {
    "network": "GLO",
    "name": "Glo Data N500 -  1.05GB - 14 days",
    "sizeGb": 1.05,
    "sizeLabel": "1.05GB",
    "price": 580,
    "validityDays": 14,
    "category": "SME",
    "providerCode": "glo500"
  },
  {
    "network": "GLO",
    "name": "Glo Data N1000 -  2.5GB - 30 days",
    "sizeGb": 2.5,
    "sizeLabel": "2.5GB",
    "price": 1150,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo1000"
  },
  {
    "network": "GLO",
    "name": "Glo Data N2000 -  5.8GB - 30 days",
    "sizeGb": 5.8,
    "sizeLabel": "5.8GB",
    "price": 2300,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo2000"
  },
  {
    "network": "GLO",
    "name": "Glo Data N2500 -  7.7GB - 30 days",
    "sizeGb": 7.7,
    "sizeLabel": "7.7GB",
    "price": 2880,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo2500"
  },
  {
    "network": "GLO",
    "name": "Glo Data N3000 -  10GB - 30 days",
    "sizeGb": 10,
    "sizeLabel": "10GB",
    "price": 3450,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo3000"
  },
  {
    "network": "GLO",
    "name": "Glo Data N4000 -  13.25GB - 30 days",
    "sizeGb": 13.25,
    "sizeLabel": "13.25GB",
    "price": 4600,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo4000"
  },
  {
    "network": "GLO",
    "name": "Glo Data N5000 -  18.25GB - 30 days",
    "sizeGb": 18.25,
    "sizeLabel": "18.25GB",
    "price": 5750,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo5000"
  },
  {
    "network": "GLO",
    "name": "Glo Data N8000 -  29.5GB - 30 days",
    "sizeGb": 29.5,
    "sizeLabel": "29.5GB",
    "price": 9200,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo8000"
  },
  {
    "network": "GLO",
    "name": "Glo Data N10000 -  50GB - 30 days",
    "sizeGb": 50,
    "sizeLabel": "50GB",
    "price": 11500,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo10000"
  },
  {
    "network": "GLO",
    "name": "Glo Data N15000 -  93GB - 30 days",
    "sizeGb": 93,
    "sizeLabel": "93GB",
    "price": 17250,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo15000"
  },
  {
    "network": "GLO",
    "name": "Glo Data N18000 -  119GB - 30 days",
    "sizeGb": 119,
    "sizeLabel": "119GB",
    "price": 20700,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo18000"
  },
  {
    "network": "GLO",
    "name": "Glo Data N1500 -  4.1GB - 30 days",
    "sizeGb": 4.1,
    "sizeLabel": "4.1GB",
    "price": 1730,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo1500"
  },
  {
    "network": "GLO",
    "name": "Glo Data N20000 -  138GB - 30 days",
    "sizeGb": 138,
    "sizeLabel": "138GB",
    "price": 23000,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo20000"
  },
  {
    "network": "GLO",
    "name": "Glo Data (SME) N70 -  200MB - 14 days",
    "sizeGb": 0.1953125,
    "sizeLabel": "200MB",
    "price": 90,
    "validityDays": 14,
    "category": "SME",
    "providerCode": "glo-dg-70"
  },
  {
    "network": "GLO",
    "name": "Glo Data (SME) N320 - 1GB 30 days",
    "sizeGb": 1,
    "sizeLabel": "1GB",
    "price": 370,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-dg-320"
  },
  {
    "network": "GLO",
    "name": "Glo Data (SME) N960 - 3GB 30 days",
    "sizeGb": 3,
    "sizeLabel": "3GB",
    "price": 1110,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-dg-960"
  },
  {
    "network": "GLO",
    "name": "Glo Data (SME) N3100 - 10GB - 30 Days",
    "sizeGb": 10,
    "sizeLabel": "10GB",
    "price": 3570,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-dg-3100"
  },
  {
    "network": "GLO",
    "name": "Glo Data (SME) N640 - 2GB 30 days",
    "sizeGb": 2,
    "sizeLabel": "2GB",
    "price": 740,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-dg-640"
  },
  {
    "network": "GLO",
    "name": "Glo Data (SME) N160 - 500MB 14 days",
    "sizeGb": 0.48828125,
    "sizeLabel": "500MB",
    "price": 190,
    "validityDays": 14,
    "category": "SME",
    "providerCode": "glo-dg-160-14"
  },
  {
    "network": "GLO",
    "name": "Glo Data (SME) N1600 - 5GB 30 days",
    "sizeGb": 5,
    "sizeLabel": "5GB",
    "price": 1840,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-dg-1600"
  },
  {
    "network": "GLO",
    "name": "45MB + 5MB Night N50 Oneoff",
    "sizeGb": 0.0439453125,
    "sizeLabel": "45MB",
    "price": 60,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-daily-50"
  },
  {
    "network": "GLO",
    "name": "115Mb + 35MB Night N100 Oneoff",
    "sizeGb": 0.1123046875,
    "sizeLabel": "115MB",
    "price": 120,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-daily-100"
  },
  {
    "network": "GLO",
    "name": "240MB + 110MB Night N200 Oneoff",
    "sizeGb": 0.234375,
    "sizeLabel": "240MB",
    "price": 230,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-2days-200"
  },
  {
    "network": "GLO",
    "name": "800MB + 1GB Night N500 Oneoff",
    "sizeGb": 1,
    "sizeLabel": "1GB",
    "price": 580,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-2weeks-500"
  },
  {
    "network": "GLO",
    "name": "1.9GB + 2GB Night N1000 Oneoff",
    "sizeGb": 1.9,
    "sizeLabel": "1.9GB",
    "price": 1150,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-monthly-1000"
  },
  {
    "network": "GLO",
    "name": "3.5GB + 4GB Night N1500 Oneoff",
    "sizeGb": 3.5,
    "sizeLabel": "3.5GB",
    "price": 1730,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-monthly-1500"
  },
  {
    "network": "GLO",
    "name": "5.2GB + 4GB Night N2000 Oneoff",
    "sizeGb": 5.2,
    "sizeLabel": "5.2GB",
    "price": 2300,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-monthly-2000"
  },
  {
    "network": "GLO",
    "name": "6.8GB + 4GB Night N2500 Oneoff",
    "sizeGb": 6.8,
    "sizeLabel": "6.8GB",
    "price": 2880,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-monthly-2500"
  },
  {
    "network": "GLO",
    "name": "10GB +4GB Night N3000 Oneoff",
    "sizeGb": 10,
    "sizeLabel": "10GB",
    "price": 3450,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-monthly-3000"
  },
  {
    "network": "GLO",
    "name": "14GB + 4GB Night N4000 Oneoff",
    "sizeGb": 14,
    "sizeLabel": "14GB",
    "price": 4600,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-monthly-4000"
  },
  {
    "network": "GLO",
    "name": "20GB + 4GB Night N5000 Oneoff",
    "sizeGb": 20,
    "sizeLabel": "20GB",
    "price": 5750,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-monthly-5000"
  },
  {
    "network": "GLO",
    "name": "27.5GB + 2GB Night N8000 Oneoff",
    "sizeGb": 27.5,
    "sizeLabel": "27.5GB",
    "price": 9200,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-monthly-8000"
  },
  {
    "network": "GLO",
    "name": "46GB + 4GB N10000 Oneoff",
    "sizeGb": 46,
    "sizeLabel": "46GB",
    "price": 11500,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-monthly-10000"
  },
  {
    "network": "GLO",
    "name": "86GB + 7GB N15000 Oneoff",
    "sizeGb": 86,
    "sizeLabel": "86GB",
    "price": 17250,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-monthly-15000"
  },
  {
    "network": "GLO",
    "name": "109GB + 10Gb N18000 Oneoff",
    "sizeGb": 109,
    "sizeLabel": "109GB",
    "price": 20700,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-monthly-18000"
  },
  {
    "network": "GLO",
    "name": "126GB + 12GB N20000 Oneoff",
    "sizeGb": 126,
    "sizeLabel": "126GB",
    "price": 23000,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-monthly-20000"
  },
  {
    "network": "GLO",
    "name": "N300 1GB Special",
    "sizeGb": 1,
    "sizeLabel": "1GB",
    "price": 350,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-special-300"
  },
  {
    "network": "GLO",
    "name": "N500 2GB Special",
    "sizeGb": 2,
    "sizeLabel": "2GB",
    "price": 580,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-special-500"
  },
  {
    "network": "GLO",
    "name": "N1500 7GB Special",
    "sizeGb": 7,
    "sizeLabel": "7GB",
    "price": 1730,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-special-1500"
  },
  {
    "network": "GLO",
    "name": "N500 3GB Weekend",
    "sizeGb": 3,
    "sizeLabel": "3GB",
    "price": 580,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-weekend-500"
  },
  {
    "network": "GLO",
    "name": "N30000 225GB Glo Mega Oneoff",
    "sizeGb": 225,
    "sizeLabel": "225GB",
    "price": 34500,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-mega-30000"
  },
  {
    "network": "GLO",
    "name": "N36000 300GB Glo Mega Oneoff",
    "sizeGb": 300,
    "sizeLabel": "300GB",
    "price": 41400,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-mega-36000"
  },
  {
    "network": "GLO",
    "name": "N50000 425GB Glo Mega Oneoff",
    "sizeGb": 425,
    "sizeLabel": "425GB",
    "price": 57500,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-mega-50000"
  },
  {
    "network": "GLO",
    "name": "N60000 525GB Glo Mega Oneoff",
    "sizeGb": 525,
    "sizeLabel": "525GB",
    "price": 69000,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-mega-60000"
  },
  {
    "network": "GLO",
    "name": "N75000 675GB Glo Mega Oneoff",
    "sizeGb": 675,
    "sizeLabel": "675GB",
    "price": 86250,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-mega-75000"
  },
  {
    "network": "GLO",
    "name": "Glo TV VOD 500 MB 3days Oneoff",
    "sizeGb": 0.48828125,
    "sizeLabel": "500MB",
    "price": 180,
    "validityDays": 3,
    "category": "DAILY",
    "providerCode": "glo-tv-150"
  },
  {
    "network": "GLO",
    "name": "Glo TV VOD 2GB 7days Oneoff",
    "sizeGb": 2,
    "sizeLabel": "2GB",
    "price": 520,
    "validityDays": 7,
    "category": "WEEKLY",
    "providerCode": "glo-tv-450"
  },
  {
    "network": "GLO",
    "name": "Glo TV VOD 6GB 30days Oneoff",
    "sizeGb": 6,
    "sizeLabel": "6GB",
    "price": 1610,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-tv-1400"
  },
  {
    "network": "GLO",
    "name": "Glo TV Lite 2GB Oneoff",
    "sizeGb": 2,
    "sizeLabel": "2GB",
    "price": 1040,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-tv-900"
  },
  {
    "network": "GLO",
    "name": "Glo TV Max 6 GB Oneoff",
    "sizeGb": 6,
    "sizeLabel": "6GB",
    "price": 3680,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-tv-3200"
  },
  {
    "network": "GLO",
    "name": "WTF N25 100MB Oneoff",
    "sizeGb": 0.09765625,
    "sizeLabel": "100MB",
    "price": 30,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-wtf-25"
  },
  {
    "network": "GLO",
    "name": "WTF N50 200MB Oneoff",
    "sizeGb": 0.1953125,
    "sizeLabel": "200MB",
    "price": 60,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-wtf-50"
  },
  {
    "network": "GLO",
    "name": "WTF N100 500MB Oneoff",
    "sizeGb": 0.48828125,
    "sizeLabel": "500MB",
    "price": 120,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-wtf-100"
  },
  {
    "network": "GLO",
    "name": "Telegram N25 20MB Oneoff",
    "sizeGb": 0.01953125,
    "sizeLabel": "20MB",
    "price": 30,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-telegram-25"
  },
  {
    "network": "GLO",
    "name": "Telegram N50 50MB Oneoff",
    "sizeGb": 0.048828125,
    "sizeLabel": "50MB",
    "price": 60,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-telegram-50"
  },
  {
    "network": "GLO",
    "name": "Telegram N100 125MB Oneoff",
    "sizeGb": 0.1220703125,
    "sizeLabel": "125MB",
    "price": 120,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-telegram-100"
  },
  {
    "network": "GLO",
    "name": "Instagram N25 20MB Oneoff",
    "sizeGb": 0.01953125,
    "sizeLabel": "20MB",
    "price": 30,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-insta-25"
  },
  {
    "network": "GLO",
    "name": "Instagram N50 50MB Oneoff",
    "sizeGb": 0.048828125,
    "sizeLabel": "50MB",
    "price": 60,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-insta-50"
  },
  {
    "network": "GLO",
    "name": "Instagram N100 125MB Oneoff",
    "sizeGb": 0.1220703125,
    "sizeLabel": "125MB",
    "price": 120,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-insta-100"
  },
  {
    "network": "GLO",
    "name": "Tiktok N25 20MB Oneoff",
    "sizeGb": 0.01953125,
    "sizeLabel": "20MB",
    "price": 30,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-tiktok-25"
  },
  {
    "network": "GLO",
    "name": "Tiktok N50 50MB Oneoff",
    "sizeGb": 0.048828125,
    "sizeLabel": "50MB",
    "price": 60,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-tiktok-50"
  },
  {
    "network": "GLO",
    "name": "Tiktok N100 125MB Oneoff",
    "sizeGb": 0.1220703125,
    "sizeLabel": "125MB",
    "price": 120,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-tiktok-100"
  },
  {
    "network": "GLO",
    "name": "Opera N25 25MB Oneoff",
    "sizeGb": 0.0244140625,
    "sizeLabel": "25MB",
    "price": 30,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-opera-25"
  },
  {
    "network": "GLO",
    "name": "Opera N50 100MB Oneoff",
    "sizeGb": 0.09765625,
    "sizeLabel": "100MB",
    "price": 60,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-opera-50"
  },
  {
    "network": "GLO",
    "name": "Opera N100 300MB Oneoff",
    "sizeGb": 0.29296875,
    "sizeLabel": "300MB",
    "price": 120,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-opera-100"
  },
  {
    "network": "GLO",
    "name": "Youtube N50 100MB Oneoff",
    "sizeGb": 0.09765625,
    "sizeLabel": "100MB",
    "price": 60,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-youtube-50"
  },
  {
    "network": "GLO",
    "name": "Youtube N100 200MB Oneoff",
    "sizeGb": 0.1953125,
    "sizeLabel": "200MB",
    "price": 120,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-youtube-100"
  },
  {
    "network": "GLO",
    "name": "Youtube N250 500MB Oneoff",
    "sizeGb": 0.48828125,
    "sizeLabel": "500MB",
    "price": 290,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-youtube-250"
  },
  {
    "network": "GLO",
    "name": "Youtube N50 500MB Oneoff",
    "sizeGb": 0.48828125,
    "sizeLabel": "500MB",
    "price": 60,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-youtube-time-50"
  },
  {
    "network": "GLO",
    "name": "Youtube N130 1.5GB Oneoff",
    "sizeGb": 1.5,
    "sizeLabel": "1.5GB",
    "price": 150,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-youtube-time-130"
  },
  {
    "network": "GLO",
    "name": "Youtube N50 500MB Night Oneoff",
    "sizeGb": 0.48828125,
    "sizeLabel": "500MB",
    "price": 60,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-youtube-night-50"
  },
  {
    "network": "GLO",
    "name": "Youtube N200 2GB Night Oneoff",
    "sizeGb": 2,
    "sizeLabel": "2GB",
    "price": 230,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-youtube-night-200"
  },
  {
    "network": "GLO",
    "name": "Glo MyG N100 400 MB OneOff (Whatsapp, Instagram, Snapchat, Boomplay, Audiomac, GloTV, Tiktok)",
    "sizeGb": 0.390625,
    "sizeLabel": "400MB",
    "price": 120,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-social-oneoff-100"
  },
  {
    "network": "GLO",
    "name": "Glo MyG N300 1 GB OneOff (Whatsapp, Instagram, Snapchat, Boomplay, Audiomac, GloTV, Tiktok)",
    "sizeGb": 1,
    "sizeLabel": "1GB",
    "price": 350,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-social-oneoff-300"
  },
  {
    "network": "GLO",
    "name": "Glo MyG N500 1.5 GB OneOff (Whatsapp, Instagram, Snapchat, Boomplay, Audiomac, GloTV, Tiktok)",
    "sizeGb": 1.5,
    "sizeLabel": "1.5GB",
    "price": 580,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-social-oneoff-500"
  },
  {
    "network": "GLO",
    "name": "Glo MyG N1000 3.5 GB OneOff (Whatsapp, Instagram, Snapchat, Boomplay, Audiomac, GloTV, Tiktok)",
    "sizeGb": 3.5,
    "sizeLabel": "3.5GB",
    "price": 1150,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "glo-social-oneoff-1000"
  },
  {
    "network": "ETISALAT",
    "name": "9mobile Data - 100 Naira - 100MB - 1 day",
    "sizeGb": 0.09765625,
    "sizeLabel": "100MB",
    "price": 120,
    "validityDays": 1,
    "category": "DAILY",
    "providerCode": "eti-100"
  },
  {
    "network": "ETISALAT",
    "name": "9mobile Data - 200 Naira - 650MB - 1 day",
    "sizeGb": 0.634765625,
    "sizeLabel": "650MB",
    "price": 230,
    "validityDays": 1,
    "category": "DAILY",
    "providerCode": "eti-200"
  },
  {
    "network": "ETISALAT",
    "name": "9mobile Data - 500 Naira - 500MB - 30 Days",
    "sizeGb": 0.48828125,
    "sizeLabel": "500MB",
    "price": 580,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "eti-500"
  },
  {
    "network": "ETISALAT",
    "name": "9mobile Data - 1000 Naira - 1.5GB - 30 days",
    "sizeGb": 1.5,
    "sizeLabel": "1.5GB",
    "price": 1150,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "eti-1000"
  },
  {
    "network": "ETISALAT",
    "name": "9mobile Data - 2000 Naira - 4.5GB Data - 30 Days",
    "sizeGb": 4.5,
    "sizeLabel": "4.5GB",
    "price": 2300,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "eti-2000"
  },
  {
    "network": "ETISALAT",
    "name": "9mobile Data - 5000 Naira - 15GB Data - 30 Days",
    "sizeGb": 15,
    "sizeLabel": "15GB",
    "price": 5750,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "eti-5000"
  },
  {
    "network": "ETISALAT",
    "name": "9mobile Data - 10000 Naira - 40GB - 30 days",
    "sizeGb": 40,
    "sizeLabel": "40GB",
    "price": 11500,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "eti-10000"
  },
  {
    "network": "ETISALAT",
    "name": "9mobile Data - 15000 Naira - 75GB - 30 Days",
    "sizeGb": 75,
    "sizeLabel": "75GB",
    "price": 17250,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "eti-15000"
  },
  {
    "network": "ETISALAT",
    "name": "9mobile Data - 27,500 Naira - 30GB - 90 days",
    "sizeGb": 30,
    "sizeLabel": "30GB",
    "price": 31630,
    "validityDays": 90,
    "category": "SME",
    "providerCode": "eti-27500"
  },
  {
    "network": "ETISALAT",
    "name": "9mobile Data - 55,000 Naira - 60GB - 180 days",
    "sizeGb": 60,
    "sizeLabel": "60GB",
    "price": 63250,
    "validityDays": 180,
    "category": "SME",
    "providerCode": "eti-55000"
  },
  {
    "network": "ETISALAT",
    "name": "9mobile Data - 110,000 Naira - 120GB - 365 days",
    "sizeGb": 120,
    "sizeLabel": "120GB",
    "price": 126500,
    "validityDays": 365,
    "category": "SME",
    "providerCode": "eti-110000"
  },
  {
    "network": "ETISALAT",
    "name": "9mobile 1GB + 100MB (1 day) - 300 Naira",
    "sizeGb": 1,
    "sizeLabel": "1GB",
    "price": 350,
    "validityDays": 1,
    "category": "DAILY",
    "providerCode": "eti-300"
  },
  {
    "network": "ETISALAT",
    "name": "9mobile 11GB (7GB+ 4GB Night) - 2,500 Naira - 30 days",
    "sizeGb": 11,
    "sizeLabel": "11GB",
    "price": 2880,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "eti-2500"
  },
  {
    "network": "ETISALAT",
    "name": "9mobile 35 GB - 7,000 Naira - 30 days",
    "sizeGb": 35,
    "sizeLabel": "35GB",
    "price": 8050,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "eti-7000"
  },
  {
    "network": "ETISALAT",
    "name": "9mobile 125GB - 20,000 Naira - 30 days",
    "sizeGb": 125,
    "sizeLabel": "125GB",
    "price": 23000,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "eti-20000"
  },
  {
    "network": "ETISALAT",
    "name": "9mobile 4GB (2GB + 2GB Night) - 1000 Naira",
    "sizeGb": 4,
    "sizeLabel": "4GB",
    "price": 1150,
    "validityDays": 30,
    "category": "SME",
    "providerCode": "eti-1000"
  },
  {
    "network": "ETISALAT",
    "name": "9mobile 7GB (6GB+1GB Night) - 7 days",
    "sizeGb": 7,
    "sizeLabel": "7GB",
    "price": 1730,
    "validityDays": 7,
    "category": "WEEKLY",
    "providerCode": "eti-1500-7"
  },
  {
    "network": "ETISALAT",
    "name": "9mobile 200MB (100MB + 100MB night) + 300secs - 1 day",
    "sizeGb": 0.1953125,
    "sizeLabel": "200MB",
    "price": 180,
    "validityDays": 1,
    "category": "DAILY",
    "providerCode": "eti-150-1"
  }
] as const
